project:
  type: website

website:
  page-navigation: true
  title: "Erratum"
  description: "A cummulation of encountered errors when developing ROS 2 applications and how to solve them."
  site-url: "https://sta210-s22.github.io/website/"

  repo-url: https://github.com/sta210-s22/website
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#626a99" # 82b0a8"

  sidebar:
    background: "#626a99" # #82b0a8"
    logo: "images/error.png"
    pinned: true
    align: center

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: Index
        href: index.qmd
format:
  html:
    theme:
      light: theme.scss #[morph, theme.scss]
      dark: [darkly, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual